apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin
  template:
    metadata:
      labels:
        name: nvidia-device-plugin
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      hostNetwork: true
      containers:
        - name: nvidia-device-plugin
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.0
          args:
            - "--config-file=/etc/nvidia-device-plugin/config.yaml"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins
              name: device-plugin
            - mountPath: /etc/nvidia-device-plugin
              name: config
            - mountPath: /dev
              name: dev
            - mountPath: /run/nvidia
              name: nvidia-run
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/rancher/k3s/agent/kubelet/device-plugins
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: nvidia-device-plugin-config
        - name: dev
          hostPath:
            path: /dev
        - name: nvidia-run
          hostPath:
            path: /run/nvidia
            type: DirectoryOrCreate
